# Generated by Django 5.2.14 on 2026-07-16 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('supply_chain', '0018_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', 'Business licence'), ('fertilizer_dealership', 'Fertilizer dealership permit'), ('cooperative_registration', 'Cooperative registration'), ('tbs_certificate', 'TBS / standards certificate'), ('other', 'Other')], max_length=40)),
                ('certificate_number', models.CharField(blank=True, max_length=120)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='organisation_certificates/')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_review', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='adminrecommendation',
            new_name='compliance__admin_d_cc637a_idx',
            old_name='compliance_a_admin_d_5fc574_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceflag',
            new_name='compliance__status_f8442d_idx',
            old_name='compliance_c_status_609ea4_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceflag',
            new_name='compliance__flagged_60d095_idx',
            old_name='compliance_c_flagged_eb54cc_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceflag',
            new_name='compliance__flagged_646dc9_idx',
            old_name='compliance_c_flagged_5df3a2_idx',
        ),
        migrations.AddField(
            model_name='organisationcertificate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_certificates', to='supply_chain.branch'),
        ),
        migrations.AddField(
            model_name='organisationcertificate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationcertificate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_certificates', to='supply_chain.supplier'),
        ),
        migrations.AddField(
            model_name='organisationcertificate',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organisationcertificate',
            index=models.Index(fields=['status'], name='compliance__status_68baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationcertificate',
            index=models.Index(fields=['expires_on', 'status'], name='compliance__expires_d16ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationcertificate',
            index=models.Index(fields=['supplier', 'status'], name='compliance__supplie_941860_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationcertificate',
            index=models.Index(fields=['branch', 'status'], name='compliance__branch__7bc6cf_idx'),
        ),
    ]
