# Generated by Django 5.1.5 on 2026-05-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('capacity_bags', models.PositiveIntegerField(default=0)),
                ('current_bags', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='certification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Certified', 'Certified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='lifecycle_state',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('RECEIVED', 'Received'), ('IN_STORAGE', 'In Storage'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('VERIFIED', 'Verified'), ('RETURNED', 'Returned'), ('EXPIRED', 'Expired')], default='IN_STORAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='quantity_tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerbatch',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='supply_chain.warehouse'),
        ),
    ]
