# Generated by Django 5.1.5 on 2026-05-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_warehouse_fertilizerbatch_certification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='supply_chain.warehouse'),
        ),
    ]
