# Generated by Django 5.2.14 on 2026-05-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0004_transfer_delivery_address_transfer_receiver_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="fertilizerbatch",
            name="date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fertilizerbatch",
            name="source_reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]