# Generated by Django 5.2.14 on 2026-07-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0017_userprofile_region_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Awaiting Verification'), ('READY', 'En Route'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
